### ISSUE TITLE
Request: Register Named Dependency

### ISSUE THREAD

**Issue by schultzcole** [hadashiA/VContainer#218]
Sometimes you might have multiple instances that could collide and it would be useful to be able to distinguish between them when resolving.

For instance:

```cs
builder.Register<Logger>(name: "StdOut", Lifetime.Singleton);
builder.Register<Logger>(name: "StdErr", Lifetime.Singleton);
```

A consumer could then specify which named logger they want injected:

```cs
class Foo 
{
    Foo([InjectNamed("StdOut")] Logger logger) { }
}

// or both!
class Bar
{
    Bar([InjectNamed("StdOut")] Logger stdLogger, [InjectNamed("StdErr")] Logger errLogger) { }
}
```

Can also be used to resolve primitives which could then be resolved throughout the container without needing to specify a `WithParameter` for every case where it is used:
```cs
builder.RegisterInstance<string>("https://www.my-url.com", name: "MyUrl");
```

**Comment by longbombus** [comment]
Maybe Parameter may become that ID which helps to resolve instance?
Ex:
```
builder.Register<Logger>(Lifetime.Singleton).WithParameter("Message").As<ILogger>();
builder.Register<Logger>(Lifetime.Singleton).WithParameter("Warning").As<ILogger>();
```
and
```
[Inject("Warning")] private ILogger warner;
```

**Comment by hadashiA** [comment]
I am against this feature.

This feature is often used for DI abuse. 
- One project I know was trying to use this feature for all kinds of generation, including Value Objects and primitive types.  If all object creation is DI, the complexity of the application will be solved by DI settings, which is difficult to understand.
- Also, using types as a key is a key feature of DI. Deviating from this seems to me to be unwieldy.

Perhaps the same thing can be done by interposing a factory instead of solving it with DI.

**Comment by hadashiA** [comment]
I have decided not to implement this feature for now.
If you have further suggestions, reopen is welcome.

**Comment by quabug** [comment]
IMO a constant string, an enum or a typed identifier are more maintainable compare to `.WithParameter("parameterName", parameterValue)` while rename a parameter.

``` c#

const string SomeParamter = "Foo";
enum SomeParmeterEnum { Foo, Bar };
class BazIdentifier {}

class SomeClass 
{
    public SomeClass([InjectNamed(SomeParameter)] string foo, [InjectName(SomeParameter.Bar)] string bar, [InjectName(typeof(BazIdentifier)] string baz) { }
}

builder.Register<SomeClass>()
    .WithNamedParameter(SomeParameter, "foo")
    .WithNamedParameter(SomeParameterEnum.Bar, "bar")
    .WithNamedParameter<BazIdentifier>("baz")
;

// compare to
builder.Register<SomeClass>()
    .WithParameter("foo", "foo")
    .WithParameter("bar", "bar")
    .WithParameter("baz", "baz")
;


```

**Comment by MeikelLP** [comment]
@hadashiA What's your recommended approach to this scenario?

I have 2 cameras:
* World renderer
* UI renderer

I want both to be injectable. 

_In Z/Extenject I would use `WithId` but that's not working right now https://github.com/modesttree/Zenject/issues/242 (this caused me to finally move to VContainer)._

**Comment by longbombus** [comment]
@MeikelLP
1. You can use two extra classes:
`[RequireComponent(typeof(Camera))] public class WorldCamera : MonoBehaviour { ... }`
and
`[RequireComponent(typeof(Camera))] public class UICamera : MonoBehaviour { ... }`.
So you can Inject them and get `Camera` by getter.
2. You can implement `interface ICameraProvider { bool TryGet(string name, out Camera camera); }` in some `MonoBehaviour` which can resolve camera without injection (if it possible, indeed). Resolve this interface to get concrete camara.
3. I do not really used [this feature](https://vcontainer.hadashikick.jp/registering/register-collection), but it looks like possible resolution. Just register multiple cameras and resolve them via `IEnumerable<Camera>`. Linear search by name (damn!), but it case of 2 cameras its ok.

**Comment by MeikelLP** [comment]
@longbombus ty I will look into it.

**Comment by JesseTG** [comment]
I think #267 would be a good use case for this.

Also, I have another use case in mind. Suppose I'm developing a game for a platform with both cloud save data and local save data, and I use the same interface to access both (in my case, [LocalStorage](https://github.com/dre0dru/LocalStorage)). However, I might want to use a different implementation for each type of save data:

- Most device configuration data (e.g. controller settings, video settings) would only need to be saved locally.
- Some configuration data relating to gameplay (like accessibility settings) should be persisted to cloud storage.
- Gameplay data should be persisted to cloud storage.
- Authentication data might also be persisted to cloud data, but not on all platforms (and therefore it might use a *third* save data service implementation).
- But on platforms without cloud storage (or if the user simply doesn't want to use it), all of the above should just be saved locally,

The same CRUD-styled API can be used in all of the above cases, but the implementation would be different.

**Comment by hadashiA** [comment]
> Suppose I'm developing a game for a platform with both cloud save data and local save data, and I use the same interface to access both (in my case, LocalStorage). However, I might want to use a different implementation for each type of save data:

If there are multiple LocalStorage implementations, why is Named Dependency the solution?

It seems to me that the solution is to create a class that further aggregates the interfaces that have Storage I/O implementations.

For example, an ILogger object is typically a single object, but an ILogger typically has multiple ILoggerProvider(s) and delegates to all of them.

**Comment by yegorsbraing** [comment]
I like VContainer a lot, but lack of `Named Dependency` limits its use too much for my usecases.

Here is usecase I'd like to have with `Named Dependency`:
  - ` IEffect`, `"ice"` - object that shows blue effect
  - `IEffect`, `"fire"` - object that shows red effect
 `Named Dependency` would make them both interchangeable without any changes in code. With limitation of `Key` to `Type` every effect would have to implement their own interface in order to be registerable, and injecting it would require rewriting part of code. Or instead of resolving object directly we resolve middle man Resolver that gets needed object using string key.

> I am against this feature.
> 
> This feature is often used for DI abuse.
> 
> * One project I know was trying to use this feature for all kinds of generation, including Value Objects and primitive types.  If all object creation is DI, the complexity of the application will be solved by DI settings, which is difficult to understand.

Can we have a concrete example of bad use?
Anyways there are still usecases that are helpful, and decision to make error in this case IMO are up to the user. Users(if they want to) will find a way to shoot their feet using even most harmless features.

For example `Transient` lifetime breaks Single Responsibility Principle by changing getter resolver into factory, and switching lifetime between `Transient` and other lifetimes will most likely cause runtime errors and require code changes. Still some people may use this feature instead of explicit factory, and consider it a good practice.

> * Also, using types as a key is a key feature of DI. Deviating from this seems to me to be unwieldy.

Also key feature of DI is to inject dependency provided by previously registered `Key` to `Value`. And `Key` can be represented by `Type` in some cases, or combination of properties in other.
Having only `Type` as `Key` is a design decision, with various benefits like performance and implementation simplicity, at cost of usage complexity. 

> Perhaps, instead of using DI to solve the problem, the same thing can be done by inserting a factory or creating a wrapped type.

Workarounds can be made to provide custom Resolver, and get object through it. This forces writing unique code each time `Named Dependency` is needed. It can be fine for someone, at the same time it would be highly convenient to have this feature out of the box from DI container, without need to change resolving code.

**Comment by c0ffeeartc** [comment]
I like VContainer a lot, but lack of `Named Dependency` limits its use too much for my usecases.

Here is usecase I'd like to have with `Named Dependency`:
  - ` IEffect`, `"ice"` - object that shows blue effect
  - `IEffect`, `"fire"` - object that shows red effect
 `Named Dependency` would make them both interchangeable without any changes in code. With limitation of `Key` to `Type` every effect would have to implement their own interface in order to be registerable, and injecting it would require rewriting part of code. Or instead of resolving object directly we resolve middle man Resolver that gets needed object using string key.

> I am against this feature.
> 
> This feature is often used for DI abuse.
> 
> * One project I know was trying to use this feature for all kinds of generation, including Value Objects and primitive types.  If all object creation is DI, the complexity of the application will be solved by DI settings, which is difficult to understand.

Can we have a concrete example of bad use?
Anyways there are still usecases that are helpful, and decision to make error in this case IMO are up to the user. Users(if they want to) will find a way to shoot their feet using even most harmless features.

For example `Transient` lifetime breaks Single Responsibility Principle by changing getter resolver into factory, and switching lifetime between `Transient` and other lifetimes will most likely cause runtime errors and require code changes. Still some people may use this feature instead of explicit factory, and consider it a good practice.

> * Also, using types as a key is a key feature of DI. Deviating from this seems to me to be unwieldy.

Also key feature of DI is to inject dependency provided by previously registered `Key` to `Value`. And `Key` can be represented by `Type` in some cases, or combination of properties in other.
Having only `Type` as `Key` is a design decision, with various benefits like performance and implementation simplicity, at cost of usage complexity. 

> Perhaps, instead of using DI to solve the problem, the same thing can be done by inserting a factory or creating a wrapped type.

Workarounds can be made to provide custom Resolver, and get object through it. This forces writing unique code each time `Named Dependency` is needed. It can be fine for someone, at the same time it would be highly convenient to have this feature out of the box from DI container, without need to change resolving code.

**Comment by juner** [comment]
`Microsoft.Extensions.DependencyInjection` seems to support named registrations starting with .NET 8.  
https://github.com/dotnet/runtime/pull/87183
