### ISSUE TITLE
Transient IDisposable classes will not get disposed when the Scope is destroyed

### ISSUE THREAD

**Issue by revolt3r** [hadashiA/VContainer#306]
I was checking the VContainer source code and it seems that for some reason only Singleton types are disposed of together with the scope.
I was wondering what is the logic to that? Both Transient and Scoped should be disposed as well.

**Comment by hadashiA** [comment]
Good point :0

Maybe It is seems my decision is mistake. As you say, Current implementation of auto-dispose feature is nothing to do for Lifetime.Transient.

But I'll point out that Lifetime.Scoped will be *Disposed*.

Reason of transient is not disposing is:
-  In game archtecture,  objects are instantiating/destroying rapidly at runtime base on any other conditions.
- So I was thinking that controlling to dispose should independent with container.

In practice, however, it is preferable not to register such objects directly in the container, using the Factory pattern or other methods.

Therefore, it is probably okay to make Trancient a Dispose target.

I've even considered changing it, but I'm hesitant because it would severely compromise compatibility.
