### ISSUE TITLE
Simple, but confusing logic of LifetimeScope.Enqueue

### ISSUE THREAD

**Issue by longbombus** [hadashiA/VContainer#319]
As I understand IContainerBuilder passed to LifetimeScope.Enqueue just adds registrations to each LifetimeScope in scene. So
```cs
using (Enqueue(
  builder =>
  {
    builder.Register<UniqueContext>(Lifetime.Singleton); // this is not Singleton for scene or prefab which context would to register
    builder.RegisterBuildCallback(c => Debug.Log("Extra scope container is ready")); // It executes every time for each scope in scene or prefab
  }
))
```
works right if loaded scene or created prefab contain only one scope.

Is it possible to make alternate Enqueue method which creates super-scope with passed builder?
Also it would be convenient to have ability to alternate IObjectResolver and LifetimeScope in hierarchy.

**Comment by hadashiA** [comment]
> Is it possible to make alternate Enqueue method which creates super-scope with passed builder?

How about this ?

```csharp
// You can find scope from loaded scene
// var parentLifetimeScope = LifetimeScope.Find<ParentLifetimeScope>();
parentLifetimeScope.CreateChild(childLifetimeScopePrefab);
```

>  it would be convenient to have ability to alternate IObjectResolver and LifetimeScope in hierarchy.

Sorry, I don't think I understand your request.
Could you provide an example of the code you want to write?

**Comment by warmerko** [comment]
There is a scenario where we want to register services in scope 1. Scope 1 also creates child scopes, for example scope 2 which also registers services, instead of just using services from parent scope 1.

We use such a scenario to load a scene and provide it with the necessary services to work. But the scene itself can create a LifetimeScope in which the registration code is called too, which seems not obvious. For example, when calling RegisterComponent, a component will be created for each child LifetimeScope inside our scene.

**Comment by Yggdrasills** [comment]
If you look through VContainerDiagnostic, you can see that on the second stage a new dependency is created on ExampleRegistration. [unitypackage](https://drive.google.com/file/d/11Z0gHe4TOyRxfTAs0gZoMFMlWJQ2NWVV/view)

**Comment by Akilaydin** [comment]
Also faced this issue in my project

**Comment by hadashiA** [comment]
Sorry, I don't fully understand the requirement.
In short, is it expected to be the parent of any scope, including `CreateChild`, `Create`, when it is Enqueued?

- I don't think LifetimeScope.CreateChild should be affected as it explicitly specifies the parent.
- As for LifetimeScope.Create, perhaps it is a timing issue that is not working.

I would like to receive specific examples of how you would like to set this up in which case. Close because this issue is old and we can no longer decide whether it is a good idea to implement the original proposal as it is. 
You are welcome to open a new issue with specific examples.
