### ISSUE TITLE
Unity's NativeCollection

### ISSUE THREAD

**Issue by hadashiA** [hadashiA/VContainer#324]
Perhaps, unity's NativeCollection faster than managed collection. Is it possible to replace some frequently accessed collection ?

**Comment by kawai125** [comment]
I think it has little effect.

The NativeContainer can store unmanaged struct only, cannot store classes or interfaces.
It maybe possible store them referenced by `System.Runtime.InteropServices.GCHandle` but it has negative impact on GC.

Essentially, the performance advantages of NativeContainer are due to 1) its internal contiguous memory area, 2) its ability to work with BurstCompiler and JobSystem, and 3) its ability to disable some error checks such as bounds checking during release builds. I don't think it makes sense to consider NativeContainer as a container that handles reference types.

**Comment by hadashiA** [comment]
Thank you for the commentary.
I think your view is valid.

I haven't found an effective part either, so I'll try to close it.
