### ISSUE TITLE
Resolve dependencies of prefab on instantiation

### ISSUE THREAD

**Issue by dre0dru** [hadashiA/VContainer#41]
Hello! Just started using VContainer and liking it, but I have a problem and can't figure out the solution. I want to create a factory that creates instances of some base class but resolves the dependencies of its descendants. Here is the example:

```
    public class ScreenService
    {

        private Dictionary<string, ScreenBase> _screenPrefabs;

        // this is the subject of question
        private SomeMagicFactory _someMagicFactory;
        
        public void Show(string screenName)
        {
            _someMagicFactory.Instatiate(_screenPrefabs[screenName]);
        }
        
        // some other code
        
    }
```
```
    public abstract class ScreenBase: MonoBehaviour
    {
        // some base class code
    }
    
    public class LoginScreen : ScreenBase
    {

        private ILoginService _loginService;

        [Inject]
        public void Construct(ILoginService loginService)
        {
            _loginService = loginService;
        }
        
        // some login screen specific code that uses ILoginService

    }

    public class SomeOtherScreen : ScreenBase
    {
        private ISomeService _someService;

        [Inject]
        public void Construct(ISomeService someService)
        {
            _someService = someService;
        }
        
        // some screen code
    }
```

With the current factory approach in VContainer I can't use one factory to instantiate/resolve dependencies at runtime in classes inherited from `ScreenBase`, because that would require me to create different factory for each class that inherits `ScreenBase`.

In Zenject, e.g. creating that sort of factory is pretty easy:
```
        public class Factory : PlaceholderFactory<UnityEngine.Object, ScreenBase>
        {
        }
```

And this factory will resolve all dependencies of classes that inherit from `ScreenBase` automatically. 

It also will resolve dependencies not only on direct descendant of `ScreenBase`, but dependencies of all MonoBehaviour classes with [Inject] attribute on target GameObject. But thats out of question, nice feature, but not required at all.

Is it possible to achieve desired behaviour with VContainer?

**Comment by hadashiA** [comment]
@dre0dru  Thanks for the good question.

My way of thinking about Factory seems to be a little different from Zenject.
Indeed, Factory is for DI to the ability to dynamically create objects, but in my opinion, this is for rather fine-grained objects, not for creating large contexts.

Let me suggest two solutions.

## Separation of control flow and Presentation/View layer

In my opinion, one of the purposes of DI is IoC (Inversion of Control).

In Unity, MonoBehaviour is the entry point for our C # code, but with DI containers we can make pure C # classes the entry point.
This means that the control flow and other domain logic can be separated from the function of MonoBehaviour as a view component.

View components are dynamically created / destroyed at run time, while all "features" such as control flow and domain logic have a more stable lifespan.

Generally speaking, it's a good idea to make the View layer stateless and separate it from control flow and data management.
This is the main reason I like DI.

My rule of thumb is that "features" (eg controllers and service classes) should be separated from View components and data-centric objects, and DI should be done primarily for the former.
Otherwise, the DI declaration will become more and more complicated.

One of my recommendations is to separate your "Screen" class from the control flow.
For example:

```csharp
builder.Register<LoginController>(Lifetime.Singleton); // long-living
builder.Register<SomeController>(Lifetime.Singleton);
```

```csharp
class LoginController : IInitializable
{
    readonly ILoginService loginService;
    readonly LoginScreen screenPrefab

    public LoginController(
        ILoginService loginService,
        LoginScreen screenPrefab)
    {
        this.loginService = loginService;
        this.screenPrefab = screenPrefab;
    }

    // This is entry point
    void IInitializable.Initialize()
    {
        // Observer patterns can also be used for inversion of control
        LoginRequestedEvent += ev =>
        {
            void screen = Instantiate(screenPrefab);
            screen.Configure(...);
        };
    }
}
```

If you want to dynamically generate the controller or service itself, consider creating a child scope.
- By doing so, it is easy to separate contexts while maintaining loose coupling of many objects in scope.
- In addition, when creating a scope, unlike a normal Factory, it is easy to control such as setting up after asynchronous loading.

```csharp
class ScreenLoader
{
    readonly LifetimeScope currentScope;

    LifetimeScope screenScope;

    public ScreenLoader(LifetimeScope currentScope)
    {
        this.currentScope = currentScope;
    }

    public void LoadScreen(string screenName)
    {
        switch (screenNAme)
        {
            case "login":
                currentScope.CreateChild(loginScreenScopePrefab);
                break;
        }
    }

    public void Unload()
    {
        screenScope.Dispose();
    }
}
```

## Using Factory

If you want to use Factory, I think there are currently two ways.

```csharp
class ScreenFactory
{
    public ScreenFactory(
        LoginScreen loginScreen,
        SomeScreen someScreen,
        ILoginService loginService,
        ISomeService someService)
    {
        // ...
    }

    public void Create(string screenName)
    {
        // ...
    }
}
```

```csharp
builder.RegisterFactory<string, ScreenBase>(container =>
{
    return screenName =>
    {
        switch (screenName)
        {
            case "login":
                var prefab = container.Resolve<LoginScreen>();
                var screen = Instantiate(prefab);
                return screen.Construct(container.Resolve<ILoginService>());
        }
    };
});

// And inject `Func<string, ScreenBase>`
```

Yes. I think this is very complicated   :disappointed_relieved:
But the truth is, I'm not very aggressive about making Factory magical.

**Comment by dre0dru** [comment]
@hadashiA Thank you for detailed answer! It seems like I have to rethink the way I use DI in general.
