### ISSUE TITLE
Naming conflict with source generator

### ISSUE THREAD

**Issue by chikacc** [hadashiA/VContainer#479]
### Description

1. Create unity project and add VContainer package
2. Add VContainer.SourceGenerator
3. Create script as following:

```cs
using VContainer;

public class Class1 {
    readonly IObjectResolver _resolver;

    public Class1(IObjectResolver resolver) => _resolver = resolver;
}
```

### Expected Behaviour

All clean, everything is happy.

### Current Behaviour

Generated `Class1GeneratedInjector.g.cs`:

```cs
 using System;
 using System.Collections.Generic;
 using VContainer;

 class Class1GeneratedInjector : IInjector
 {
     public object CreateInstance(IObjectResolver resolver, IReadOnlyList<IInjectParameter> parameters)
     {
         var resolver = resolver.ResolveOrParameter(typeof(global::VContainer.IObjectResolver), "resolver", parameters);
         var instance = new Class1((global::VContainer.IObjectResolver)resolver);
         Inject(instance, resolver, parameters);
         return instance;
     }

     public void Inject(object instance, IObjectResolver resolver, IReadOnlyList<IInjectParameter> parameters)
     {
         return;
     }
 }
```

Unity console shown as follows:

```
VContainer.SourceGenerator\VContainer.SourceGenerator.VContainerSourceGenerator\Class1GeneratedInjector.g.cs(9,14): error CS0136: A local or parameter named 'resolver' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
VContainer.SourceGenerator\VContainer.SourceGenerator.VContainerSourceGenerator\Class1GeneratedInjector.g.cs(9,25): error CS0841: Cannot use local variable 'resolver' before it is declared
VContainer.SourceGenerator\VContainer.SourceGenerator.VContainerSourceGenerator\Class1GeneratedInjector.g.cs(11,27): error CS1503: Argument 2: cannot convert from 'object' to 'VContainer.IObjectResolver'
```

### Environment

- VContainer 1.13.0
- Unity 2021.3.16f1
- Windows 11 21H2

**Comment by hadashiA** [comment]
Thanks for the report. I'll fix it.

**Comment by spikeliu1984** [comment]
`VContainer.SourceGenerator\VContainer.SourceGenerator.VContainerSourceGenerator\MessagePipe.VContainer.ObjectResolverProxyGeneratedInjector.g.cs(11,18): error CS0136: A local or parameter named 'resolver' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
VContainer.SourceGenerator\VContainer.SourceGenerator.VContainerSourceGenerator\MessagePipe.VContainer.ObjectResolverProxyGeneratedInjector.g.cs(11,29): error CS0841: Cannot use local variable 'resolver' before it is declared
VContainer.SourceGenerator\VContainer.SourceGenerator.VContainerSourceGenerator\MessagePipe.VContainer.ObjectResolverProxyGeneratedInjector.g.cs(13,31): error CS1503: Argument 2: cannot convert from 'object' to 'VContainer.IObjectResolver'`
Not sure if it's the same problem. I'm seeing the same error when MessagePipe is imported.

Environment
VContainer 1.13.0
Unity 2022.2.8f1

**Comment by th3d0g** [comment]
I'm also having this issue related to [MessagePipe](https://github.com/Cysharp/MessagePipe) and [InGameDebugger](https://github.com/yasirkula/UnityIngameDebugConsole).

`VContainer.SourceGenerator\VContainer.SourceGenerator.VContainerSourceGenerator\MessagePipe.VContainer.ObjectResolverProxyGeneratedInjector.g.cs(11,18): error CS0136: A local or parameter named 'resolver' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter`

`VContainer.SourceGenerator\VContainer.SourceGenerator.VContainerSourceGenerator\IngameDebugConsole.ConsoleMethodInfoGeneratedInjector.g.cs(11,111): error CS0841: Cannot use local variable 'parameters' before it is declared`

VContainer 1.13.0
Unity 2021.3.13f1


Please advise.

**Comment by chikacc** [comment]
@spikeliu1984 @th3d0g 

I have a way to avoid these similar problems until #480's pull request is released.
Place the source generator in a separate assembly definition, e.g. VContainer.Generators, it seems that then MessagePipe or any definition assembly will not trigger the source generator, unless you add VContainer.Generators to the reference.

**Comment by hadashiA** [comment]
@chikacc @spikeliu1984 @th3d0g  Sorry for the late response.

I've released a fix.  https://github.com/hadashiA/VContainer/releases/tag/1.13.1
If you still have problems, please reopen.
